-- MySQL Script generated by MySQL Workbench
-- Tue Feb 18 11:29:14 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema aml20o
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `aml20o` ;

-- -----------------------------------------------------
-- Schema aml20o
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aml20o` DEFAULT CHARACTER SET utf8mb4 ;
SHOW WARNINGS;
USE `aml20o` ;

-- -----------------------------------------------------
-- Table `aml20o`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aml20o`.`customer` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `aml20o`.`customer` (
  `cus_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cus_fname` VARCHAR(15) NOT NULL,
  `cus_lname` VARCHAR(30) NOT NULL,
  `cus_street` VARCHAR(30) NOT NULL,
  `cus_city` VARCHAR(30) NOT NULL,
  `cus_state` CHAR(2) NOT NULL,
  `cus_zip` INT ZEROFILL NOT NULL,
  `cus_phone` BIGINT UNSIGNED NOT NULL,
  `cus_email` VARCHAR(100) NOT NULL,
  `cus_balance` DECIMAL(8,2) NOT NULL,
  `cus_total_sales` DECIMAL(8,2) NOT NULL,
  `cus_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`cus_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `aml20o`.`petstore`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aml20o`.`petstore` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `aml20o`.`petstore` (
  `pst_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pst_name` VARCHAR(30) NOT NULL,
  `pst_street` VARCHAR(30) NOT NULL,
  `pst_city` VARCHAR(30) NOT NULL,
  `pst_state` CHAR(2) NOT NULL,
  `pst_zip` INT(9) ZEROFILL NOT NULL,
  `pst_phone` BIGINT NOT NULL,
  `pst_email` VARCHAR(100) NOT NULL,
  `pst_url` VARCHAR(100) NOT NULL,
  `pst_ytd_sales` DECIMAL(10,2) NOT NULL,
  `pst_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`pst_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `aml20o`.`pet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aml20o`.`pet` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `aml20o`.`pet` (
  `pet_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pst_id` SMALLINT UNSIGNED NOT NULL,
  `cus_id` SMALLINT UNSIGNED NULL,
  `pet_type` VARCHAR(45) NOT NULL,
  `pet_sex` ENUM('m', 'f') NOT NULL,
  `pet_cost` DECIMAL(6,2) NOT NULL,
  `pet_price` DECIMAL(6,2) NOT NULL,
  `pet_age` TINYINT NOT NULL,
  `pet_color` VARCHAR(30) NOT NULL,
  `pet_sale_date` DATE NULL,
  `pet_vaccine` ENUM('y', 'n') NOT NULL,
  `pet_neuter` ENUM('y', 'n') NOT NULL,
  `pet_notes` VARCHAR(235) NULL,
  PRIMARY KEY (`pet_id`),
  INDEX `fk_pet_customer_idx` (`cus_id` ASC) VISIBLE,
  INDEX `fk_pet_petstore1_idx` (`pst_id` ASC) VISIBLE,
  CONSTRAINT `fk_pet_customer`
    FOREIGN KEY (`cus_id`)
    REFERENCES `aml20o`.`customer` (`cus_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pet_petstore1`
    FOREIGN KEY (`pst_id`)
    REFERENCES `aml20o`.`petstore` (`pst_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `aml20o`.`customer`
-- -----------------------------------------------------
START TRANSACTION;
USE `aml20o`;
INSERT INTO `aml20o`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Travis', 'Henry', '123 Main St', 'Austin', 'TX', 448222311, 21374800225, 'thenry@gmail.com', 23.70, 482.18, NULL);
INSERT INTO `aml20o`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Cindy', 'Diaz', '19475 Sw 118th Ave', 'Miami', 'FL', 331867355, 30591762887, 'cindywindy@hotmail.com', 9.22, 12.45, NULL);
INSERT INTO `aml20o`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Nathan', 'Rodriguez', '909 Lemon Rd', 'Orlando', 'FL', 398665711, 4079930011, 'natrod@gmail.com', 209.01, 3453.06, NULL);
INSERT INTO `aml20o`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Sally', 'Priolo', '1259 N Gay St', 'Tampa', 'FL', 300558671, 2428909687, 'salprolo@hotmail.com', 91.34, 400.75, NULL);
INSERT INTO `aml20o`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Pedro', 'Leon', '673 Learning Way', 'San Francisco', 'CA', 280573817, 3451974561, 'leonpedro@gmail.com', 184.82, 694.59, NULL);
INSERT INTO `aml20o`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Amanda', 'Martinez', '892 Ne 122nd St', 'Painesville', 'OH', 440077854, 4561239506, 'aamandamartinez@yahoo.com', 21.49, 691.26, NULL);
INSERT INTO `aml20o`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Samantha', 'White', '9428 Homewood St', 'Stone Mountain', 'GA', 300836574, 7763198380, 'samwhite@hotmail.com', 82.03, 157.44, NULL);
INSERT INTO `aml20o`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Luis', 'Gonzalez', '64 Mountainview Lane', 'Fredericksburg', 'VA', 224050078, 3885019338, 'luisgonzalezz@gmail.com', 10.33, 2570.47, NULL);
INSERT INTO `aml20o`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Sarah', 'Andrade', '7732 Longfellow Dr', 'Lawrence', 'GA', 341160405, 4038245359, 'sarahandrade@gmail.com', 107.30, 225.67, NULL);
INSERT INTO `aml20o`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Brandon', 'Soto', '973 Birchwood Lane', 'Germantown', 'MD', 839084032, 9685104893, 'sotobrandon@yahoo.com', 55.02, 556.21, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `aml20o`.`petstore`
-- -----------------------------------------------------
START TRANSACTION;
USE `aml20o`;
INSERT INTO `aml20o`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Pet Palace', '1827 Sw 25th St', 'Miami', 'FL', 331966623, 3059683315, 'petpalace@gmail.com', 'https://www.petpalace.com', 55000, NULL);
INSERT INTO `aml20o`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Carole\'s Critters', '813 W Pensacola', 'Tallahassee', 'FL', 323040036, 8508593321, 'carolescritters@hotmail.com', 'https://www.carolescritters.com', 34000, NULL);
INSERT INTO `aml20o`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Furry Friends', '30350 Stapleton Drive', 'Tampa', 'FL', 357653484, 8137559004, 'furryfriends@yahoo.com', 'https://www.furryfriends.com', 40000, NULL);
INSERT INTO `aml20o`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Forever Friends', '876 Nw 2nd St', 'Chicago', 'IL', 929831046, 5243451166, 'foreverfriends@gmail.com', 'https://www.foreverfriends.com', 42000, NULL);
INSERT INTO `aml20o`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Tammy\'s Pets', '324 Sally Dr', 'Atlanta', 'GA', 644934421, 7384782344, 'tammyspets@yahoo.com', 'https://www.tammyspets.com', 59000, NULL);
INSERT INTO `aml20o`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Ruby\'s Reptiles', '97 E 26th St', 'Pensacola', 'FL', 983411883, 8293812083, 'rubysreptiles@yahoo.com', 'https://www.rubysreptiles.com', 58000, NULL);
INSERT INTO `aml20o`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Pet Hotel', '933 Main St', 'Sacramento', 'CA', 229384332, 9445712425, 'pethotel@hotmail.com', 'https://www.pethotel.com', 64000, NULL);
INSERT INTO `aml20o`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Paws and More', '283 N Tennessee St', 'Orlando', 'FL', 338476048, 8933748223, 'pawsandmore@gmail.com', 'https://www.pawsandmore.com', 87000, NULL);
INSERT INTO `aml20o`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Puppy Heaven ', '9384 Ne 24th Ave', 'Valdosta', 'GA', 872683117, 9287783312, 'puppyheaven@gamil.com', 'https://www.puppyheaven.com', 70000, NULL);
INSERT INTO `aml20o`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Kittykats', '939 Lorene Dr', 'Phoenix', 'AZ', 829925961, 3455069002, 'kittykats@hotmail.com', 'https://www.kittykats.com', 68500, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `aml20o`.`pet`
-- -----------------------------------------------------
START TRANSACTION;
USE `aml20o`;
INSERT INTO `aml20o`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 1, 5, 'Schnauzer', 'f', 800, 1200, 1, 'Salt and Pepper', '2021-10-02', 'y', 'n', NULL);
INSERT INTO `aml20o`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 2, 1, 'Jack Russell Terrier ', 'm', 300, 400, 2, 'White/tan', NULL, 'y', 'n', NULL);
INSERT INTO `aml20o`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 6, 5, 'American Shorthair', 'm', 100, 250, 10, 'Gray', '2018-12-09', 'y', 'y', NULL);
INSERT INTO `aml20o`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 9, 9, 'Pitbull ', 'f', 50, 200, 1, 'Gray', '2022-05-01', 'n', 'n', NULL);
INSERT INTO `aml20o`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 3, 2, 'Rattlesnake ', 'f', 80, 220, 55, 'Black', NULL, 'n', 'n', NULL);
INSERT INTO `aml20o`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 6, 4, 'Ragdoll', 'f', 400, 500, 3, 'White/gray', '2021-11-15', 'y', 'n', NULL);
INSERT INTO `aml20o`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 1, 8, 'Chow Chow', 'm', 500, 900, 4, 'White/tan', '2024-04-09', 'y', 'y', NULL);
INSERT INTO `aml20o`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 8, 6, 'Siamese Cat', 'f', 550, 780, 8, 'White', '2019-03-23', 'n', 'y', NULL);
INSERT INTO `aml20o`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 5, 2, 'Maine Coon', 'm', 800, 1000, 1, 'Black', '2020-06-17', 'y', 'y', NULL);
INSERT INTO `aml20o`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 7, 4, 'Turtle', 'f', 80, 300, 60, 'Green', '2015-07-29', 'n', 'n', NULL);

COMMIT;

